language: php
php:
  - 5.6
  - 7.1
  
before_script: 
  - composer install --dev --no-interaction --prefer-source
  - touch ./.env
  - touch ./database/database_testing.sqlite
  - php artisan migrate --database=sqlite_testing --no-interaction
  
script: phpunit --configuration phpunit.xml --coverage-text
